# Generated by Django 5.2.5 on 2025-08-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='room', max_length=100),
        ),
    ]
